### PR TITLE
Fixes #575 nested uses.

### LINKED ISSUE #575: Unexpected key uses
[api.zip](https://github.com/raml-org/raml-java-parser/files/2677578/api.zip)

When parsing the attached api an "Unexpected key uses is thrown".

### PR DESCRIPTION
**Pull request by pacafuentes**

### CODE REVIEW

File: raml-parser-2/src/main/java/org/raml/v2/internal/impl/v10/grammar/Raml10Grammar.java [hunk 1]
```diff
@@ -15,57 +15,26 @@
...
-import org.raml.v2.internal.impl.commons.nodes.ExampleDeclarationNode;
-import org.raml.v2.internal.impl.commons.nodes.ExamplesNode;
-import org.raml.v2.internal.impl.commons.nodes.ExtendsNode;
-import org.raml.v2.internal.impl.commons.nodes.ExternalSchemaTypeExpressionNode;
-import org.raml.v2.internal.impl.commons.nodes.FacetNode;
-import org.raml.v2.internal.impl.commons.nodes.ResponseNode;
-import org.raml.v2.internal.impl.commons.nodes.TypeDeclarationField;
-import org.raml.v2.internal.impl.commons.nodes.TypeDeclarationNode;
-import org.raml.v2.internal.impl.commons.nodes.TypesNode;
+import org.raml.v2.internal.impl.commons.nodes.*;
```
Comment (dfmacias) [inline raml-parser-2/src/main/java/org/raml/v2/internal/impl/v10/grammar/Raml10Grammar.java]: import *

File: raml-parser-2/src/main/java/org/raml/v2/internal/impl/v10/grammar/Raml10Grammar.java [hunk 2]
```diff
@@ -826,7 +825,7 @@ private KeyValueRule propertyField()
         return field(scalarType(), anyOf(inlineType(), propertyType())).then(PropertyNode.class);
     }
 
-    private ObjectRule propertyType()
+    ObjectRule propertyType()
```
Comment (dfmacias) [inline raml-parser-2/src/main/java/org/raml/v2/internal/impl/v10/grammar/Raml10Grammar.java]: Can this be `protected` instead of `package-private`?
