### PR TITLE
The Api object method version() may violate its signature return type

### LINKED ISSUE #248: The Api object method version() may violate its signature return type
## Affects [1.0.0](https://github.com/raml-org/raml-java-parser/tree/1.0.0)

**Issue**
The `version()` method provided by the Api object returns an `AnnotableSimpleType<String>`, which in turn provides a `value()` method that returns a `String`.

However it may return an `Integer` or a `BigDecimal` depending on the content of the version in the raml declaration.

## How to reproduce
```yaml
#%RAML 1.0
title: Api
version: 1
```
`api.version().value()` returns an Integer

```yaml
#%RAML 1.0
title: Api
version: 1.0
```
`api.version().value()` returns an BigDecimal

**Java File**
```java
import org.raml.v2.api.RamlModelBuilder;
import org.raml.v2.api.RamlModelResult;
import org.raml.v2.api.model.v10.api.Api;

public class Test {

    @org.junit.Test
    public void testRaml10Import() throws Exception {

        String savedRamlLocation = Test.class.getResource("your/path/api.raml").toString();
        RamlModelResult ramlModelResult = new RamlModelBuilder().buildApi(savedRamlLocation);

        Api savedRaml = ramlModelResult.getApiV10();
        assertTrue(savedRaml.version().value() instanceof String);
    }
}
```

### PR DESCRIPTION
**Pull request by LorenaSoledad**
Fixes #248

### CODE REVIEW

File: raml-parser-2/src/main/java/org/raml/v2/api/model/v10/system/types/PlainString.java [hunk 1]
```diff
@@ -0,0 +1,23 @@
...
+ * Unless required by applicable law or agreed to in writing,
+ * software distributed under the License is distributed on an
+ * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
+ * either express or implied. See the License for the specific
+ * language governing permissions and limitations under the License.
+ */
+package org.raml.v2.api.model.v10.system.types;
+
+
+public interface PlainString extends AnnotableSimpleType<String>
```
Comment (machaval) [inline raml-parser-2/src/main/java/org/raml/v2/api/model/v10/system/types/PlainString.java]: Shouldn't this be called AnnotableStringType?

Comment (svacas) [inline raml-parser-2/src/main/java/org/raml/v2/api/model/v10/system/types/PlainString.java]: `PlainString` looks more aligned with `MarkdownString` that we already have, but `AnnotableStringType` looks like a better option given the parent interface name.
