### PR TITLE
Example validation failure when using union types with logical OR and…

### LINKED ISSUE #254: Example validation failure when using union types with logical OR and optional property
## Affects [1.0.0](https://github.com/raml-org/raml-java-parser/tree/1.0.0)

**Issue**
Given a union type with logical OR referencing two types that each declare a different enum (or pattern) on the same **optional** property.
If an instance of this union type can match any of the 2 possible types, examples defined are only validated against one of types' enum (or pattern), leading to an error.

If the property is no longer set as optional, the validation occurs without problem.

NB: The example shows an array, but it works the same for a regular union

## How to reproduce
`file api.ram`
```yaml
#%RAML 1.0
title: Toto API

types:
 FirstOption:
   properties:
     theProperty?:
       enum: [a,b]
 SecondOption:
   properties:
     theProperty?:
       enum: [c,d]
 Item:
   properties:
     testProperty:
       type: (FirstOption | SecondOption)[]
   example:
     testProperty:
       - theProperty: c
```

**Java File**
```java
import org.raml.v2.api.RamlModelBuilder;
import org.raml.v2.api.RamlModelResult;

public class Test {

    @org.junit.Test
    public void testRaml10Import() throws Exception {

        String savedRamlLocation = Test.class.getResource("your/path/api.raml").toString();
        RamlModelResult ramlModelResult = new RamlModelBuilder().buildApi(savedRamlLocation);

    }
}
```

### PR DESCRIPTION
**Pull request by LorenaSoledad**
… optional property

Fixes #254

### CODE REVIEW

File: yagi/src/main/java/org/raml/yagi/framework/grammar/rule/ObjectRule.java [hunk 1]
```diff
@@ -117,16 +117,17 @@ public ObjectRule named(String ruleName)
         return result;
     }
 
-    private boolean matchesAny(KeyValueRule rule, List<Node> children)
+    private Node matchesAny(KeyValueRule rule, List<Node> children)
```
Comment (machaval) [inline yagi/src/main/java/org/raml/yagi/framework/grammar/rule/ObjectRule.java]: We should change the name of this to findMachingNode with @Nullable
