### PR TITLE
Cannot parse AnnotationTypeDeclaration and DocumentationItem

### LINKED ISSUE #253: Cannot parse AnnotationTypeDeclaration and DocumentationItem
#### AnnotationTypeDeclaration

When trying to parse the RAML definition from [this ticket](https://github.com/raml-org/raml-js-parser-2/issues/358) (without allowedTarget) I get an error:

```
java.lang.IllegalStateException: Invalid ramlNode type (TypeDeclarationNode) or fragment (AnnotationTypeDeclaration) combination
```

WIth a documentation item [taken from RAML examples](https://github.com/raml-org/raml-examples/blob/master/others/alainn-mobile-shopping/docs/security.raml): 

```
https://github.com/raml-org/raml-java-parser/issues/253
```

It fails with allowedTarget saying it is unexpected.
#### DocumentationItem

When trying to import the documentation item [in the RAML examples](https://github.com/raml-org/raml-examples/blob/master/others/alainn-mobile-shopping/docs/security.raml): 

```
java.lang.IllegalStateException: Invalid ramlNode type (DocumentationItemNode) or fragment (DocumentationItem) combination
```
#### RAML files

``` yaml
#%RAML 1.0 DocumentationItem
  title: Security
  content: |
    # Policy

    Though the API does not implement any authentication / authorisation logic itself, it is dependent on the user details which the Ping Federate Token enforcement policy leaves in context so as to correlate the personal calls mentioned in the section on Resource Hierarchy above. 
```

``` yaml
#%RAML 1.0 AnnotationTypeDeclaration

displayName: Method handler function path
properties:
  path:
    type: string
    description: |
      A string that is passed to the pathResolver function in order to return
      a route handler function.
    examples:
      example1:
        description: |
          A relative file that export a default function
        value: './folderrfolder/file.js'
      example2:
        description: |
          Dot separated path to method
        value: 'server.controllers.user.findUser'
  config?:
    type: object
    description: |
      Config object will be passed as the first parameter to the controller on every call
```
#### Java file

``` java
package com.restlet.definitions.raml10.reader;

import org.raml.v2.api.RamlModelBuilder;
import org.raml.v2.api.RamlModelResult;

import static org.junit.Assert.fail;

public class Test {

    @org.junit.Test
    public void test() throws Exception {
        String savedRamlLocation = Test.class.getResource("fileName").toString();
        RamlModelResult ramlModelResult = new RamlModelBuilder().buildApi(savedRamlLocation);
        if (ramlModelResult.hasErrors()) {
            fail("Should pass parser validation");
        }
    }
}
```

### PR DESCRIPTION
**Pull request by LorenaSoledad**
Fixes #253

### CODE REVIEW

File: raml-parser-2/src/main/java/org/raml/v2/api/RamlModelResult.java [hunk 1]
```diff
@@ -263,6 +274,16 @@ public ExampleSpec getExampleSpec()
         return exampleSpec;
     }
 
+    /**
+     * @return the RAML NamedExample v1.0 parsed without errors
```
Comment (svacas) [inline raml-parser-2/src/main/java/org/raml/v2/api/RamlModelResult.java]: fix javadoc s/NamedExample/DocumentationItme/, also fix the one for resource types though it was there before
