### PR TITLE
Inconsistency in JSON Schema validation for type "date"

### LINKED ISSUE #289: Inconsistency in JSON Schema validation for type "date"
Having the following RAML:

``` yaml
#%RAML 1.0
title: Test API
version: 1.0

/subscription:
  post:
    body:
      application/json:
        schema: !include schema.json
        example: !include example.json
```

Where `schema.json` is:
```json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"type": "object",
	"properties": {
		"numberOfPeople": {
			"type": "number",
			"minimum": 0,
			"maximum": 90
		},
		"startDate": {
			"type": "string",
			"format": "date"
		}
	},
	"required": [
		"numberOfPeople",
		"startDate"
	]
}
```

And `example.json` is:

```json
{
	"numberOfPeople": 90,
	"startDate": "2016-08-23T18:25:43-05:00"
}
```

`requestedStartDate` is defined as **date**, but the example is in **date-time**. However, when parsing this RAML, the output is:

`No errors found.`

but it should inform that the format is invalid.

Finally, if you set `numberOfPeople` to a value higher than 90 the output is:

```
1 error found:

       	- Error validating JSON. Error: {
error: numeric instance is greater than the required maximum (maximum: 90, found: 92)
    level: "error"
    schema: {"loadingURI":"file:/Users/lorenadaicich/MuleSoft/10-parser/raml-parser-2/src/test/resources/org/raml/v2/parser/schemas/json-with-warnings/schema.json#","pointer":"/properties/numberOfPeople"}
    instance: {"pointer":"/numberOfPeople"}
    domain: "validation"
    keyword: "maximum"
    maximum: 90
    found: 92
,
warning: format attribute "date" not supported
    level: "warning"
    schema: {"loadingURI":"file:/Users/lorenadaicich/MuleSoft/10-parser/raml-parser-2/src/test/resources/org/raml/v2/parser/schemas/json-with-warnings/schema.json#","pointer":"/properties/startDate"}
    domain: "validation"
    keyword: "format"
    attribute: "date"

} [line=10, col=18]
```

**Expected output**

### PR DESCRIPTION
**Pull request by LorenaSoledad**
Fixes #289

### CODE REVIEW

File: raml-parser-2/src/test/java/org/raml/v2/api/SystemPropertiesTestCase.java [hunk 1]
```diff
@@ -0,0 +1,76 @@
...
+import static org.junit.Assert.assertThat;
+import static org.junit.Assert.assertTrue;
+
+import static org.raml.v2.internal.impl.commons.rule.JsonSchemaValidationRule.JSON_SCHEMA_FAIL_ON_WARNING_KEY;
+
+public class SystemPropertiesTestCase
+{
+    private String failOnWarningOldValue;
+
+    @Before
```
Comment (svacas) [inline raml-parser-2/src/test/java/org/raml/v2/api/SystemPropertiesTestCase.java]: should be applied @After running the test

Comment (LorenaSoledad) [inline raml-parser-2/src/test/java/org/raml/v2/api/SystemPropertiesTestCase.java]: @svacas Done.
