### PR TITLE
Fixes #536 Exception when having an example with a value greater than…

### LINKED ISSUE #536: Exception thrown when having an example with a value greater than Long.MAX_VALUE
Given this RAML:

```
#%RAML 1.0
title: Exception when format

types:
  LongNumber:
    type: number
    format: long
    minimum: 1
    maximum: 9223372036854775807
    
  ObjectType:
    type: object
    properties: 
      property: LongNumber
    examples:
     -example: | 
       { "property":12345678901234567890 }
```

An exception is thrown when parsing it.

### PR DESCRIPTION
**Pull request by pacafuentes**
… Long.MAX_VALUE.

### CODE REVIEW

File: yagi/src/main/java/org/raml/yagi/framework/grammar/rule/AllOfRule.java [hunk 1]
```diff
@@ -102,6 +105,8 @@ public Node apply(@Nonnull Node node)
         for (Rule rule : rules)
         {
             node = rule.apply(node);
+            if (isErrorResult(node))
+                return createNodeUsingFactory(node);
```
Comment (dfmacias) [inline yagi/src/main/java/org/raml/yagi/framework/grammar/rule/AllOfRule.java]: Why do you return a new node instead of the failing one?
