### PR TITLE
Schema validation in request should give more information

### LINKED ISSUE #247: Schema validation in request should give more information
Taking the following RAML as an example:

``` yaml
#%RAML 1.0
title: Example
baseUri: http://base.uri/
schemas:
    - UserJson: |
          {
             "$schema": "http://json-schema.org/draft-04/schema",
             "type": "object",
             "properties": {
               "firstname":  { "type": "string" },
               "lastname":  { "type": "string" },
               "age":  { "type": "integer" }
             },
             "required": [ "firstname", "lastname" ]
          }

/endpoint:
    post:
        body:
            application/json:
                schema: UserJson
                example: 
```

**Expected result**
When the parser validates an example in `/endpoint` against the schema previously defined, it should give more information about where in the example the error occurred, e.g. the key.

**Actual result:**
The parser is only giving a simple message that the example is wrong.

### PR DESCRIPTION
**Pull request by LorenaSoledad**
Fixes #247

### CODE REVIEW

File: yagi/src/main/java/org/raml/yagi/framework/grammar/rule/ErrorNodeFactory.java [hunk 1]
```diff
@@ -69,7 +70,13 @@ public static Node createRequiredValueNotFound(Node node, Rule keyRule)
 
     public static Node createInvalidType(Node node, NodeType type)
     {
-        return new ErrorNode("Invalid type " + node.getType() + ", expected " + type);
+        StringBuilder message = new StringBuilder("Invalid type " + node.getType() + ", expected " + type);
+        if (node.getParent() != null && node.getParent() instanceof KeyValueNode)
+        {
+            message.append(" (key: \"" + ((KeyValueNode) node.getParent()).getKey() + "\")");
```
Comment (machaval) [inline yagi/src/main/java/org/raml/yagi/framework/grammar/rule/ErrorNodeFactory.java]: Why are we only adding this to this error message only?

**Comment by LorenaSoledad** [comment]
The requirement is to give more info when validating a request body against its type definition. One of the changes was done in the schema validator to use all the data it gives. The second change is when the data type is defined in RAML format... And if it is something wrong it will show this message.

**Comment by machaval** [comment]
I get the schema validation message improvement. My concern with the second
change is that it affects any rule validation not just the body one. Any
rule type mismatch. But I don't see this additional information as
something wrong I see it useful that is why I don't see why not adding it
to all error message and be consistent.
