### PR TITLE
Fixes #444 Validation fails when using uses inside a DataType fragment.

### LINKED ISSUE #444: Validation fails when using uses inside a DataType fragment that is reference from a root raml
[uses-bug.zip](https://github.com/raml-org/raml-java-parser/files/1589812/uses-bug.zip)
  When parsing given raml validation fails with Unexpected key 'uses'

### PR DESCRIPTION
**Pull request by pacafuentes**

### CODE REVIEW

File: raml-parser-2/src/main/java/org/raml/v2/internal/impl/commons/nodes/RamlTypedFragmentDefault.java [hunk 1]
```diff
@@ -15,27 +15,27 @@
...
+import org.raml.v2.internal.impl.commons.phase.RamlTypedFragment;
 import org.raml.v2.internal.impl.v10.grammar.Raml10Grammar;
+import org.raml.yagi.framework.nodes.AbstractObjectNode;
+import org.raml.yagi.framework.nodes.Node;
 import org.raml.yagi.framework.util.NodeSelector;
 
 import javax.annotation.Nonnull;
 
-public class RamlTypedFragmentNode extends AbstractObjectNode implements LibraryNodeProvider, ContextProviderNode
+public class RamlTypedFragmentDefault extends AbstractObjectNode implements RamlTypedFragment
```
Comment (dfmacias) [inline raml-parser-2/src/main/java/org/raml/v2/internal/impl/commons/nodes/RamlTypedFragmentDefault.java]: I prefer the name **DefaultRamlTypedFragment**

File: raml-parser-2/src/main/java/org/raml/v2/internal/impl/commons/nodes/TypeDeclarationNodeFragment.java [hunk 2]
```diff
@@ -0,0 +1,67 @@
...
+
+import org.raml.v2.api.model.v10.RamlFragment;
+import org.raml.v2.internal.impl.commons.phase.RamlTypedFragment;
+import org.raml.v2.internal.impl.v10.grammar.Raml10Grammar;
+import org.raml.yagi.framework.nodes.Node;
+import org.raml.yagi.framework.util.NodeSelector;
+
+import javax.annotation.Nonnull;
+
+import static org.raml.v2.api.model.v10.RamlFragment.*;
```
Comment (dfmacias) [inline raml-parser-2/src/main/java/org/raml/v2/internal/impl/commons/nodes/TypeDeclarationNodeFragment.java]: Avoid using "import *"

File: raml-parser-2/src/main/java/org/raml/v2/internal/impl/commons/nodes/TypeDeclarationNodeFragment.java [hunk 3]
```diff
@@ -0,0 +1,67 @@
...
+public class TypeDeclarationNodeFragment extends TypeDeclarationNode implements RamlTypedFragment
+{
+
+    private Node libraryNode;
+
+    @Nonnull
+    @Override
+    public Node getContextNode()
+    {
+        return getLibraryNode() != null || getParent() == null ? this : org.raml.yagi.framework.util.NodeUtils.getContextNode(getParent());
```
Comment (dfmacias) [inline raml-parser-2/src/main/java/org/raml/v2/internal/impl/commons/nodes/TypeDeclarationNodeFragment.java]: You can replace the qualified name with import
