### PR TITLE
Fixes #458 Cast class Error when including a dataType inside a dataType.

### LINKED ISSUE #458: Cast class Error when including a dataType inside a dataType
[include-data-type.zip](https://github.com/raml-org/raml-java-parser/files/1764253/include-data-type.zip)

When parsing the attached RAML the following error is thrown
_Raml parser uncaught exception: org.raml.yagi.framework.nodes.ErrorNode cannot be cast to org.raml.yagi.framework.nodes.KeyValueNode_

### PR DESCRIPTION
**Pull request by pacafuentes**

### CODE REVIEW

File: raml-parser-2/src/main/java/org/raml/v2/internal/impl/commons/phase/RamlFragmentGrammarTransformer.java [hunk 1]
```diff
@@ -20,12 +20,14 @@
...
 
+import static org.raml.v2.internal.utils.RamlNodeUtils.isErrorResult;
+
 public class RamlFragmentGrammarTransformer implements Transformer
 {
     @Override
     public boolean matches(Node node)
     {
-        return node instanceof RamlTypedFragment && node.getParent() != null;
+        return node instanceof RamlTypedFragment && node.getParent() != null && !isErrorResult(node);
```
Comment (dfmacias) [inline raml-parser-2/src/main/java/org/raml/v2/internal/impl/commons/phase/RamlFragmentGrammarTransformer.java]: shouldn't this be added to all transformer/phases?

Comment (pacafuentes) [reply raml-parser-2/src/main/java/org/raml/v2/internal/impl/commons/phase/RamlFragmentGrammarTransformer.java]: It could be a good approach, but I didn't want to make a change with such impact
